//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grimoire {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grimoire.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutLbl {
            get {
                return ResourceManager.GetString("aboutLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Clear.
        /// </summary>
        public static string autoClear_chk {
            get {
                return ResourceManager.GetString("autoClear_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Convert.
        /// </summary>
        public static string autoConvert_chk {
            get {
                return ResourceManager.GetString("autoConvert_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear on List Change.
        /// </summary>
        public static string clear_on_change {
            get {
                return ResourceManager.GetString("clear_on_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ID:.
        /// </summary>
        public static string dataId_lbl {
            get {
                return ResourceManager.GetString("dataId_lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a field.
        /// </summary>
        public static string descLbl {
            get {
                return ResourceManager.GetString("descLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted:.
        /// </summary>
        public static string encLbl {
            get {
                return ResourceManager.GetString("encLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string ext_grpBx {
            get {
                return ResourceManager.GetString("ext_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension:.
        /// </summary>
        public static string extLbl {
            get {
                return ResourceManager.GetString("extLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string grid_grpBx {
            get {
                return ResourceManager.GetString("grid_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string inputLbl {
            get {
                return ResourceManager.GetString("inputLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string inst_flipBtn {
            get {
                return ResourceManager.GetString("inst_flipBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string inst_grpBx {
            get {
                return ResourceManager.GetString("inst_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string inst_inputLbl {
            get {
                return ResourceManager.GetString("inst_inputLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string inst_outLbl {
            get {
                return ResourceManager.GetString("inst_outLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string msg_grpBx {
            get {
                return ResourceManager.GetString("msg_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-File.
        /// </summary>
        public static string multi_grpBx {
            get {
                return ResourceManager.GetString("multi_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string newLbl {
            get {
                return ResourceManager.GetString("newLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string noBtn {
            get {
                return ResourceManager.GetString("noBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        public static string offsetLbl {
            get {
                return ResourceManager.GetString("offsetLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string okBtn {
            get {
                return ResourceManager.GetString("okBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append (ascii).
        /// </summary>
        public static string optAppend_ascii_rBtn {
            get {
                return ResourceManager.GetString("optAppend_ascii_rBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Options.
        /// </summary>
        public static string optGrid_grpBx {
            get {
                return ResourceManager.GetString("optGrid_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Options:.
        /// </summary>
        public static string optName_grpBx {
            get {
                return ResourceManager.GetString("optName_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string optNone_rBtn {
            get {
                return ResourceManager.GetString("optNone_rBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove (ascii).
        /// </summary>
        public static string optRemove_ascii_rBtn {
            get {
                return ResourceManager.GetString("optRemove_ascii_rBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string rebuildBtn {
            get {
                return ResourceManager.GetString("rebuildBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search_grpBx {
            get {
                return ResourceManager.GetString("search_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string sizeLbl {
            get {
                return ResourceManager.GetString("sizeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string stats_grpBx {
            get {
                return ResourceManager.GetString("stats_grpBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitFlag Editor.
        /// </summary>
        public static string ts_bitflag_editor {
            get {
                return ResourceManager.GetString("ts_bitflag_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        public static string ts_encLbl {
            get {
                return ResourceManager.GetString("ts_encLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string ts_file_load {
            get {
                return ResourceManager.GetString("ts_file_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ts_file_new {
            get {
                return ResourceManager.GetString("ts_file_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string ts_file_rebuild {
            get {
                return ResourceManager.GetString("ts_file_rebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDB.
        /// </summary>
        public static string ts_file_save_rdb {
            get {
                return ResourceManager.GetString("ts_file_save_rdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string ts_load {
            get {
                return ResourceManager.GetString("ts_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ts_load_file {
            get {
                return ResourceManager.GetString("ts_load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string ts_load_sql {
            get {
                return ResourceManager.GetString("ts_load_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string ts_log_viewer {
            get {
                return ResourceManager.GetString("ts_log_viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ts_save {
            get {
                return ResourceManager.GetString("ts_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string ts_save_enc {
            get {
                return ResourceManager.GetString("ts_save_enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ts_save_file {
            get {
                return ResourceManager.GetString("ts_save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string ts_save_file_csv {
            get {
                return ResourceManager.GetString("ts_save_file_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string ts_save_file_sql {
            get {
                return ResourceManager.GetString("ts_save_file_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string ts_save_sql {
            get {
                return ResourceManager.GetString("ts_save_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ASCII).
        /// </summary>
        public static string ts_save_w_ascii {
            get {
                return ResourceManager.GetString("ts_save_w_ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure:.
        /// </summary>
        public static string ts_structLb {
            get {
                return ResourceManager.GetString("ts_structLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string ts_utilities {
            get {
                return ResourceManager.GetString("ts_utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Path:.
        /// </summary>
        public static string upPathLbl {
            get {
                return ResourceManager.GetString("upPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesBtn {
            get {
                return ResourceManager.GetString("yesBtn", resourceCulture);
            }
        }
    }
}
